package com.focusflow.entity;

/**
 * Enumeration representing different types of AI suggestions generated by Gemini.
 */
public enum RecommendationType {
    PRIORITIZATION,
    BREAKDOWN,
    FOCUS_PLAN,
    REPLAN,
    INSIGHT
}
